name: CI-pipeline

on: [push]

jobs:
  build:
    name: Clone
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH
        uses: cross-the-world/ssh-pipeline@master
      with:
        user: ${{ secrets.USERNAME }}
        pass: ${{ secrets.PASSWORD }}
      - run: cd Orange-IT 
      - run: git status
   
