name: Build Project

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: isbang/compose-action@v1.0.0
        with:
          compose-file: './docker-compose.yml'
          down-flags: '--volumes'
      - run: docker-compose build

