name: CI-pipeline

on: [push]

jobs:
  build:
    name: Login
    runs-on: ubuntu-latest
    steps:
    - name: scp pipelines
      uses: cross-the-world/ssh-scp-ssh-pipelines@latest
      with:
        user: ${{ secrets.USERNAME }}
        pass: ${{ secrets.PASSWORD }}
    - name: Clone GitHub repository
      run: git clone git@github.com:INT222-014-027-118/Orange-IT.git
      

