name: CI-pipeline

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Login
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: 22
        script: |
          mkdir test12
    # - name: Clone GuillaumeFalourd/formulas-training PRIVATE repository
    #   uses: GuillaumeFalourd/clone-github-repo-action@v1
    #   with:
    #     owner: 'INT222-014-027-118'
    #     repository: 'Orange-IT'
    #     access-token: ${{ secrets.ACCESS_TOKEN }}
    # - name: Clone GitHub repository
    #   run: |
    #     git clone https://github.com/INT222-014-027-118/Orange-IT.git
    #     ${{ secrets.ACCESS_TOKEN }}
    # - name: Access cloned repository content
    #   run: |
    #     cd Orang-IT
    #     ls -l
    # - name: test
    #   run: |    
    #     mkdir test
