name: CI-pipeline

on: [push]

jobs:
  build:
    name: Login
    runs-on: ubuntu-latest
    steps:
    - name: scp pipelines
      uses: cross-the-world/ssh-scp-ssh-pipelines@latest
      with:
        user: ${{ secrets.USERNAME }}
        pass: ${{ secrets.PASSWORD }}
    # - name: Clone GuillaumeFalourd/formulas-training PRIVATE repository
    #   uses: GuillaumeFalourd/clone-github-repo-action@v1
    #   with:
    #     owner: 'INT222-014-027-118'
    #     repository: 'Orange-IT'
    #     access-token: ${{ secrets.ACCESS_TOKEN }}
    - name: Clone GitHub repository
      run: |
        git clone https://github.com/INT222-014-027-118/Orange-IT.git
        ${{ secrets.ACCESS_TOKEN }}
        
    - name: Access cloned repository content
      run: |
        cd Orang-IT
        ls -l
