name: CI-pipeline

on: [push]

jobs:
  build:
    name: Clone
    runs-on: ubuntu-latest
    steps:
    - name: Login VM
      run: ssh ${{ secrets.USERNAME }}
      run: ${{ secrets.PASSWORD }}

      # uses: cross-the-world/ssh-pipeline@v1.2.0
      # with:
      #   user: 
      #   pass: 
      # - run: cd Orange-IT 
      # - run: git status
   
