name: CI-CD_pipeline

on: 
 pull_request:
    branches:
      - master
    types: [closed]
jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Login to VM, build and deploy
      uses: appleboy/ssh-action@master
      with:
        host: 20.212.7.255
        username: orange
        password: orange_014027118
        script: |
          cd Orange-IT
          git pull origin master
          docker-compose up -d --build 
