name: CI-pipeline

on: [push]

jobs:
  build:
    name: Clone
    runs-on: ubuntu-latest
    steps:
    - name: ssh-pipeline
      uses: cross-the-world/ssh-pipeline@v1.2.0
      with:
        user: ${{ secrets.USERNAME }}
        pass: ${{ secrets.PASSWORD }}
      - run: cd Orange-IT 
      - run: git status
   
